---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-operator-system
  labels:
    app.kubernetes.io/name: hello-operator
    app.kubernetes.io/managed-by: kustomize
    control-plane: controller-manager
