---
# Inventaire Ansible — Azure AKS
all:
  children:
    aks:
      hosts:
        aks_cluster:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
