//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Run `make generate` to regenerate this file.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *HelloWorld) DeepCopyInto(out *HelloWorld) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this HelloWorld object.
func (in *HelloWorld) DeepCopy() *HelloWorld {
	if in == nil {
		return nil
	}
	out := new(HelloWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface for HelloWorld.
func (in *HelloWorld) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this HelloWorldList into another HelloWorldList.
func (in *HelloWorldList) DeepCopyInto(out *HelloWorldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelloWorld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this HelloWorldList object.
func (in *HelloWorldList) DeepCopy() *HelloWorldList {
	if in == nil {
		return nil
	}
	out := new(HelloWorldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface for HelloWorldList.
func (in *HelloWorldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this HelloWorldSpec into another HelloWorldSpec.
func (in *HelloWorldSpec) DeepCopyInto(out *HelloWorldSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy returns a deep copy of this HelloWorldSpec object.
func (in *HelloWorldSpec) DeepCopy() *HelloWorldSpec {
	if in == nil {
		return nil
	}
	out := new(HelloWorldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this HelloWorldStatus into another HelloWorldStatus.
func (in *HelloWorldStatus) DeepCopyInto(out *HelloWorldStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this HelloWorldStatus object.
func (in *HelloWorldStatus) DeepCopy() *HelloWorldStatus {
	if in == nil {
		return nil
	}
	out := new(HelloWorldStatus)
	in.DeepCopyInto(out)
	return out
}
